### ISSUE TITLE
Helm with OCI registry

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/sveltos#270]
Add an example using OCI registry, for instance following one (and call out that for OCI charts, the chartName needs to have whole URL)

```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: vault
spec:
  clusterSelector: env=fv
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    oci://registry-1.docker.io/bitnamicharts/vault
    repositoryName:   oci-vault
    chartName:        oci://registry-1.docker.io/bitnamicharts/vault
    chartVersion:     0.7.2
    releaseName:      vault
    releaseNamespace: vault
    helmChartAction:  Install
```
