### ISSUE TITLE
Question: dynamic flux path

### ISSUE THREAD

**Issue by gdlx** [projectsveltos/sveltos#278]
Hello,

I couldn’t find this information in the documentation, so I’m not sure if it’s possible: Is there a way to dynamically set a policyRef path using the cluster env or name?

Here’s the use case: We’re currently using Flux with generated YAML files stored in a Git repository. These files are organized into directories for each environment and cluster, like so: `manifests/prod/my-prod-cluster/`

I’d like to use Sveltos to push bootstrap manifests from the same source. However, the path would be different for each cluster. Therefore, I need to manage a ClusterProfile like this:

```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: kyverno-policies
spec:
  clusterSelector: env=prod
  policyRefs:
  - kind: GitRepository
    name: manifests
    namespace: flux-system
    path: manifests/{{ cluster.labels.env }}/{{ cluster.name }}/kyverno-policices
  dependsOn: 
  - kyverno
```

Another side question: Is it possible to use Sveltos without continuous sync to avoid conflict with FluxCD ? As I aim at using the same source repo, I'd like it to bootstrap new clusters but not to do any change once the cluster is ready.

Thanks !

**Comment by gianlucam76** [comment]
Hi @gdlx thank you.

Regarding your second question the answer is yes. Set SyncMode to "OneTime"
In that case, when a cluster matches a ClusterProfile for the very first time, all addons and applications in the ClusterProfile will be deployed by sveltos on the cluster.

After that, any modification to ClusterProfile won't propagate to the cluster.

Regarding your first question, that is not currently possible. But I love the idea (it's very much in line with Sveltos philosophy). So I will add it. It should be easy so I can give you and image to try by end of the week.

**Comment by gianlucam76** [comment]
Change was extremely easy: https://github.com/projectsveltos/addon-controller/pull/533

will create a patch release v0.29.1

**Comment by gianlucam76** [comment]
Verified with this:

1. With flux pointing to https://github.com/gianlucam76/yaml_flux

2. Added annotations "environment: nginx-ingress"

3. Deployed 
```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: deploy-nginx-ingress
spec:
  clusterSelector: env=fv
  policyRefs:
  - kind: GitRepository
    name: flux-system
    namespace: flux-system
    path: '{{ index .Cluster.metadata.annotations "environment" }}'
```

Sveltos instantiate path to "nginx-ingress" and deployed the content in that directory
