### ISSUE TITLE
Feature Request: Provide an MCS Controller Implementation Using Sveltos’s Event Framework

### ISSUE THREAD

**Issue by kahirokunn** [projectsveltos/sveltos#435]
## Proposal

I propose a feature (or guideline documentation) illustrating how to implement an MCS (Multi-Cluster Services) controller using Sveltos’s Event Framework.

The solution adheres to [KEP-1645: Multi-Cluster Services API](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api) and implements the **"dummy" or "shadow" Service approach** recommended in the KEP for compatibility with existing kube-proxy implementations.

### KEP-1645 Implementation Approach

The [Kubernetes MCS API (KEP-1645)](https://github.com/kubernetes/enhancements/blob/master/keps/sig-multicluster/1645-multi-cluster-services-api/README.md) standardizes how services can be exported from one cluster and discovered in others. The KEP specifically outlines an implementation strategy that maintains compatibility with existing Kubernetes networking components:

> *"Existing implementations of Kubernetes Service API (e.g. kube-proxy) can be extended to present `ServiceImports` alongside traditional `Services`. One often discussed implementation requiring no changes to kube-proxy is to have the mcs-controller maintain ServiceImports and create "dummy" or "shadow" Service objects, named after a mcs-controller managed EndpointSlice that aggregates all cross-cluster backend IPs, so that kube-proxy programs those endpoints like a regular Service."*
>
> — [KEP-1645: Multi-Cluster Services API](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api#implementation-details)

### Why This Approach?

This "shadow Service" approach provides several critical advantages:

1. **Zero kube-proxy Changes**: No modifications required to existing Kubernetes networking stack
2. **Standard Service Discovery**: Applications can use standard Kubernetes service discovery mechanisms
3. **Transparent Load Balancing**: kube-proxy handles multi-cluster endpoint load balancing automatically
4. **DNS Compatibility**: CoreDNS and other DNS providers work seamlessly with the generated Services

## Benefits

- Fully Automated Creation: Eliminates manual steps for provisioning MCS resources across clusters.  
- Unified Approach for Multiple Service Types: ClusterIP, NodePort, and LoadBalancer services are all converted consistently (with optional special handling for headless).  
- Clean Resource Ownership: OwnerReferences let Kubernetes handle garbage collection automatically, simplifying lifecycle management.  
- DNS-Friendly for Headless Services: CoreDNS can resolve these exported headless services, thanks to the EndpointSlice objects.  
- Extensible Design: Sveltos’s Event Framework can be extended to track additional resource states or integrate with other multi-cluster components if needed.

By following the strategies outlined above and implementing them in Sveltos’s Event Framework, platform engineers can reliably export services from any source cluster and consume them with minimal configuration overhead. This significantly accelerates multi-cluster use cases—whether for high availability, traffic optimization, or cross-environment integrations—without inventing a proprietary approach.

# MCS Controller Implementation Guide Using Sveltos

## Overview
This guide details how to automate the implementation of the Kubernetes Multi-Cluster Services (MCS) API using Sveltos's Event Framework.  
Based on KEP-1645 and the principle of namespace sameness, we present accurate conversion patterns for each service type.

In this revised document, we introduce the concept of creating derived Services named `derived-$hashServiceExport,` where $hash is computed from the ServiceExport name. Refer to the following implementation for hashing:
https://github.com/kubernetes-sigs/mcs-api/blob/b4f72b8c11b640b049a2c247994a2de3eb0dda75/pkg/controllers/common.go#L39-L43

We also create one EndpointSlice for each source cluster associated with the ServiceExport, named `derived-$hash-$clusterId.` For clarity, the label `multicluster.kubernetes.io/service-name: <clusterset service name>` is added to both the EndpointSlice and the derived Service. Additionally, we establish OwnerReferences from the ServiceImport to the Service, and from the Service to the EndpointSlice.

## Processing Patterns by Service Type

For reference:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-multicluster/1645-multi-cluster-services-api/README.md#clusterset-service-behavior-expectations

### 1. ClusterIP / LoadBalancer / NodePort Services

These service types can be handled with the same processing pattern. Below is an example:

#### Original Service in Source Cluster (ClusterID: cluster-a)

```yaml
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  type: ClusterIP  # or LoadBalancer or NodePort
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 8080
```

#### ServiceExport in Source Cluster (ClusterID: cluster-a)

```yaml
apiVersion: multicluster.k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: web-service
  namespace: default
```

#### ClusterIP Service generated in cluster-a and cluster-b

```yaml
apiVersion: v1
kind: Service
metadata:
  name: derived-$hashServiceExport
  namespace: default
  labels:
    multicluster.kubernetes.io/service-name: web-service
    multicluster.kubernetes.io/service-imported: "true"
    app.kubernetes.io/managed-by: sveltos
  ownerReferences:
  - apiVersion: multicluster.k8s.io/v1alpha1
    kind: ServiceImport
    name: web-service
    # other fields (uid, controller, blockOwnerDeletion) required by OwnerReference
spec:
  type: ClusterIP
  selector:  # Selector is maintained based on namespace sameness
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 8080
```

#### ServiceImport generated in cluster-a and cluster-b

```yaml
apiVersion: multicluster.k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: web-service
  namespace: default
  annotations:
    multicluster.kubernetes.io/derived-service: derived-$hashServiceExport
spec:
  type: ClusterSetIP
  ports:
    - name: http
      port: 80
      protocol: TCP
  ips:
    - "10.96.0.1"  # Cluster IP assigned to the derived Service. eg. kubectl get svc derived-$hashServiceExport -o yaml | yq '.spec.clusterIp'
status:
  clusters:
  - cluster: cluster-a
```

#### EndpointSlice generated in cluster-a and cluster-b

```yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: derived-$hashServiceExport-cluster-a
  namespace: default
  labels:
    kubernetes.io/service-name: derived-$hashServiceExport
    multicluster.kubernetes.io/service-name: web-service
    cluster.x-k8s.io/cluster-name: cluster-a
    endpointslice.kubernetes.io/managed-by: sveltos
  ownerReferences:
  - apiVersion: multicluster.k8s.io/v1alpha1
    kind: ServiceImport
    name: web-service
    # other fields (uid, controller, blockOwnerDeletion) required by OwnerReference
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "10.0.1.1"
    conditions:
      ready: true
    nodeName: node-a
  - addresses:
      - "10.0.1.2"
    conditions:
      ready: true
    nodeName: node-b
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: derived-$hashServiceExport-cluster-b
  namespace: default
  labels:
    kubernetes.io/service-name: derived-$hashServiceExport
    multicluster.kubernetes.io/service-name: web-service
    cluster.x-k8s.io/cluster-name: cluster-b
    endpointslice.kubernetes.io/managed-by: sveltos
  ownerReferences:
  - apiVersion: multicluster.k8s.io/v1alpha1
    kind: ServiceImport
    name: web-service
    # other fields (uid, controller, blockOwnerDeletion) required by OwnerReference
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "10.0.1.3"
    conditions:
      ready: true
    nodeName: node-a
  - addresses:
      - "10.0.1.4"
    conditions:
      ready: true
    nodeName: node-b
```

### 2. Headless Services (clusterIP: None)

https://github.com/coredns/multicluster/blob/49f47d950355f793d656aec8a6d198daf1d888b1/multicluster.go#L347-L381

Headless services require special handling, typically relying on DNS-based service discovery instead of a VIP (Virtual IP). Initially, one might assume an MCS controller only needs to create ServiceImport objects; however, since CoreDNS uses EndpointSlices as a record source (reference: https://github.com/coredns/multicluster/blob/49f47d950355f793d656aec8a6d198daf1d888b1/multicluster.go#L347-L381), the controller must also create EndpointSlices for each source cluster for correct DNS-based service discovery.

#### Original Service in Source Cluster (ClusterId: cluster-a)

```yaml
apiVersion: v1
kind: Service
metadata:
  name: stateful-service
  namespace: default
spec:
  clusterIP: None
  selector:
    app: stateful
  ports:
    - name: http
      port: 80
      targetPort: 8080
```

#### ServiceExport in Source Cluster (ClusterId: cluster-a)

```yaml
apiVersion: multicluster.k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: stateful-service
  namespace: default
```

#### ServiceImport generated in cluster-a and cluster-b

```yaml
apiVersion: multicluster.k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: stateful-service
  namespace: default
  annotations:
    multicluster.kubernetes.io/derived-service: derived-$hashServiceExport
spec:
  type: Headless
  ports:
    - name: http
      port: 80
      protocol: TCP
status:
  clusters:
  - cluster: cluster-a
```

#### EndpointSlice generated in cluster-a and cluster-b

```yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: derived-$hashServiceExport-cluster-a
  namespace: default
  labels:
    kubernetes.io/service-name: stateful-service
    multicluster.kubernetes.io/service-name: stateful-service
    cluster.x-k8s.io/cluster-name: cluster-a
    endpointslice.kubernetes.io/managed-by: sveltos
  ownerReferences:
  - apiVersion: multicluster.k8s.io/v1alpha1
    kind: ServiceImport
    name: web-service
    # other fields (uid, controller, blockOwnerDeletion) required by OwnerReference
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "10.0.2.1"
    conditions:
      ready: true
    nodeName: node-c
  - addresses:
      - "10.0.2.2"
    conditions:
      ready: true
    nodeName: node-d
```

### 3. ExternalName Services

ExternalName services cannot be exported.

#### Original Service in Source Cluster (ClusterId: cluster-a)

```yaml
apiVersion: v1
kind: Service
metadata:
  name: external-db
  namespace: default
spec:
  type: ExternalName
  externalName: db.example.com
```

#### ServiceExport (ClusterId: cluster-a)

```yaml
apiVersion: multicluster.k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: external-db
  namespace: default
```

This ServiceExport will fail with the following status:

```yaml
apiVersion: multicluster.k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: external-db
  namespace: default
status:
  conditions:
    - type: InvalidService
      status: "True"
      reason: UnsupportedServiceType
      message: "ExternalName services cannot be exported"
```

## Key Implementation Points

1. **Selector Maintenance**
   - Following namespace sameness principles, all imported Services maintain their selectors.
   - This enables Pods with matching labels in the importing cluster to be automatically added as service endpoints when applicable.

2. **(Optional) Derived Service Names**
   - For each ServiceExport, create a derived Service named `derived-$hashServiceExport` where $hash is computed from the ServiceExport name.  
   - One EndpointSlice per source cluster is created for every exported service. The EndpointSlice is named `derived-$hashServiceExport-$clusterId.`

3. **CoreDNS Integration for Headless Services**
   - Although the IP address resolution for headless services is handled by CoreDNS, actual EndpointSlices are still required because they serve as data sources for DNS records.
   - Since there is no difference in EndpointSlices themselves between Headless and ClusterIP services, there is no need for conditional branching - you can process them exactly the same way as EndpointSlices for other services.

4. **Labeling for Multi-Cluster**
   - EndpointSlices should include the label `multicluster.kubernetes.io/service-name: <clusterset service name>,` which is required by the KEP.  
   - For better UX and resource management, we also recommend adding the same label to the derived Service.

5. **(Optional) OwnerReferences for Automatic Garbage Collection**
   - The ServiceImport object is set as the owner of the derived Service.  
   - The derived Service is set as the owner of the EndpointSlice.  
   - This hierarchy allows you to track resource relationships efficiently and simplifies finalizer handling.

6. **Service Type Conversion**
   - LoadBalancer and NodePort services are converted to ClusterIP in the derived Services.
   - For headless services (clusterIP: None), create corresponding headless services in target clusters to maintain DNS resolution consistency. This allows CoreDNS to create EndpointSlices containing IPs of Pods matching the headless service's selector, adhering to namespace sameness.
   - ExternalName services cannot be exported.

7. **Conflict Resolution**
   - Only one ServiceImport is created when the same service is exported from multiple clusters (i.e., we do not create per-cluster ServiceImport objects).
   - Warnings are issued when mixing headless and non-headless services.  
   - Conflicts are communicated via ServiceExport Conditions.

8. **Scalability and Error Handling**
   - Efficient EndpointSlice updates minimize inter-cluster communication overhead.  
   - Validation failures are reflected in ServiceExport status conditions.  
   - A retry mechanism should handle transient resource creation or update issues.

9. **(Optional) Monitoring and Debugging**
   - Resources are labeled appropriately for easier traceability and debugging.  
   - Events are recorded for state changes.  
   - Metrics can be exported to monitor the MCS controller’s performance and potential bottlenecks.

## Architectural Considerations

1. **Sveltos's Role**
   - Detection of ServiceExports.  
   - (Optional) Monitoring of ServiceExports.  
   - Automatic creation and cleanup of EndpointSlice, derived Service, and ServiceImport objects.  
   - State synchronization across clusters.

2. **Namespace Sameness**
   - The same namespace structure must exist across clusters to avoid conflicts.  
   - Proper synchronization of namespace resources is assumed (integrations with Sveltos’s CRDs or other tooling).

**Comment by gianlucam76** [comment]
Thank you @kahirokunn 

Let me summarise it to see if I got it. 

- When a ServiceExport is created in ClusterA: 
    . Sveltos gets the corresponding Kubernetes Service and Endpoints and creates an EndpointSlice
        * this is supposed to be created in the other clusters part of the clusterSet
        * in your example port is https/443. Is this a constant? 
    . Sveltos create a ServiceImport in the other clusters part of the clusterSet 
    . if corresponding Kubernetes Service does not exist, Sveltos creates a Service with no selector  and type ClusterSetIP in the other clusters part of the clusterSet
   
Is that correct?

**Comment by gianlucam76** [comment]
Thank you. This is achievable already with Sveltos. Next week (I am pretty tight this week), I will prepare the Sveltos configuration for this and share. 
We can make sure we create only one ServiceImport by collecting all ServiceExports in the management cluster and then aggregating from there before posting ServiceImports in the other clusters.

I might need your help testing it though.

**Comment by kahirokunn** [comment]
Please allow me to re-read the KEP and share the revised version with you.

# MCS Controller Implementation Guide Using Sveltos - Revised

## Overview
This guide details how to automate the implementation of Kubernetes Multi-Cluster Services (MCS) API using Sveltos's Event Framework. 
Based on KEP-1645 and namespace sameness principles, we present accurate conversion patterns for each service type.

## Processing Patterns by Service Type

https://github.com/kubernetes/enhancements/blob/master/keps/sig-multicluster/1645-multi-cluster-services-api/README.md#clusterset-service-behavior-expectations

### 1. ClusterIP / LoadBalancer / NodePort Services

These service types can be handled with the same processing pattern. Here's an example:

#### Original Service in Source Cluster (Cluster A)
```yaml
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  type: ClusterIP  # or LoadBalancer or NodePort
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 8080
```

#### ServiceExport (Cluster A)
```yaml
apiVersion: multicluster.k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: web-service
  namespace: default
```

#### Generated EndpointSlice (Cluster B)
```yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  generateName: web-service-
  namespace: default
  labels:
    kubernetes.io/service-name: web-service
    cluster.x-k8s.io/cluster-name: cluster-a
    app.kubernetes.io/managed-by: sveltos
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "10.0.1.1"
    conditions:
      ready: true
    nodeName: node-a
  - addresses:
      - "10.0.1.2"
    conditions:
      ready: true
    nodeName: node-b
```

#### Generated Service (Cluster B)
```yaml
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
  labels:
    multicluster.kubernetes.io/service-imported: "true"
    app.kubernetes.io/managed-by: sveltos
spec:
  type: ClusterIP  # LoadBalancer and NodePort are converted to ClusterIP
  selector:        # Selector is maintained based on namespace sameness
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 8080
```

#### Generated ServiceImport (Cluster B)
```yaml
apiVersion: multicluster.k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: web-service
  namespace: default
spec:
  type: ClusterSetIP
  ports:
    - name: http
      port: 80
      protocol: TCP
  ips:
    - "10.96.0.1"  # Cluster IP assigned to the Service
```

### 2. Headless Services (clusterIP: None)

https://github.com/coredns/multicluster

Headless services require special handling. They use DNS-based service discovery instead of VIP.

#### Original Service in Source Cluster (Cluster A)
```yaml
apiVersion: v1
kind: Service
metadata:
  name: stateful-service
  namespace: default
spec:
  clusterIP: None
  selector:
    app: stateful
  ports:
    - name: http
      port: 80
      targetPort: 8080
```

#### ServiceExport (Cluster A)
```yaml
apiVersion: multicluster.k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: stateful-service
  namespace: default
```

#### Generated Service (Cluster B)
```yaml
apiVersion: v1
kind: Service
metadata:
  name: stateful-service
  namespace: default
  labels:
    multicluster.kubernetes.io/service-imported: "true"
    app.kubernetes.io/managed-by: sveltos
spec:
  clusterIP: None
  selector:
    app: stateful
  ports:
    - name: http
      port: 80
      targetPort: 8080
```

#### Generated ServiceImport (Cluster B)
```yaml
apiVersion: multicluster.k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: stateful-service
  namespace: default
spec:
  type: Headless  # Special type for headless services
  ports:
    - name: http
      port: 80
      protocol: TCP
  # ips field is not required for headless services
```

### 3. ExternalName Services

ExternalName services cannot be exported.

#### Original Service in Source Cluster (Cluster A)
```yaml
apiVersion: v1
kind: Service
metadata:
  name: external-db
  namespace: default
spec:
  type: ExternalName
  externalName: db.example.com
```

#### ServiceExport (Cluster A)
```yaml
apiVersion: multicluster.k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: external-db
  namespace: default
```

This ServiceExport will fail with the following status:
```yaml
apiVersion: multicluster.k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: external-db
  namespace: default
status:
  conditions:
    - type: InvalidService
      status: "True"
      reason: UnsupportedServiceType
      message: "ExternalName services cannot be exported"
```

## Key Implementation Points

1. **Selector Maintenance**
   - Following namespace sameness principles, all imported Services maintain their selectors
   - This allows Pods with matching labels in the importing cluster to automatically become service endpoints

2. **Special Handling for Headless Services**
   - EndpointSlices are not created
   - ServiceImport uses `type: Headless`
   - DNS resolution is handled by `coredns/multicluster`
   - Supports DNS names in the format `<hostname>.<clusterid>.<service>.<namespace>.svc.clusterset.local`

3. **Service Type Conversion**
   - LoadBalancer and NodePort are converted to ClusterIP
   - Headless services maintain their headless nature
   - ExternalName services cannot be exported

4. **Conflict Resolution**
   - Only one ServiceImport is created when the same service is exported from multiple clusters
   - Warnings are issued when mixing headless and non-headless services
   - Conflicts are communicated via ServiceExport Conditions and events

## Architectural Considerations

1. **Sveltos's Role**
   - Detection and monitoring of ServiceExports
   - Automatic creation of resources (EndpointSlice, Service, ServiceImport)
   - State synchronization between clusters

2. **Scalability**
   - Efficient EndpointSlice updates
   - Minimizing inter-cluster communication overhead

3. **Error Handling**
   - Strict implementation of ServiceExport validation
   - Conflict detection and appropriate warning display
   - Retry mechanism for resource creation failures

4. **Monitoring and Debugging**
   - Appropriate labels on all resources
   - Event recording for state changes
   - Metrics for troubleshooting
