### ISSUE TITLE
Feature Request: Support ControllerIdentity in Sveltos similar to CAPA

### ISSUE THREAD

**Issue by kahirokunn** [projectsveltos/sveltos#440]
## Overview
I would like to introduce functionality similar to CAPA's `AWSClusterControllerIdentity` in Sveltos. This would allow us to prevent issues like expiration of `xxx-sveltos-kubeconfig` Secrets and potentially remove the create permission for `serviceaccount/token`.

## Motivation
- Protection from `xxx-sveltos-kubeconfig` Secret expiration
  - For example, if you stop all mgmt cluster nodes for two weeks to save money during vacation, the token might expire during that period.
- Remove create permission for `serviceaccount/token`
- Currently, CAPA has a ControllerIdentity resource that allows for staged assumption of multiple IAM roles, and we want to maintain compatibility with this.
  - In Sveltos, we want to add a ControllerIdentity CRD as a similar mechanism and link it with `identityRef`
  - This will allow us to minimize Controller execution permissions and follow best practices for services like EKS.

### 1. New CRD: ControllerIdentity
- Define ControllerIdentity in Sveltos and allow specifying `identityRef` in `SveltosCluster` as follows:
```yaml
apiVersion: lib.projectsveltos.io/v1beta1
kind: SveltosCluster
metadata:
  labels:
    sveltos-agent: present
  name: mgmt
  namespace: mgmt
spec:
  identityRef:
    kind: ControllerIdentity
    name: default
---
apiVersion: lib.projectsveltos.io/v1beta1
kind: ControllerIdentity
metadata:
  name: "default"
spec:
  allowedNamespaces: {}  # Allow usage in all Namespaces
```
- Include fields like `allowedNamespaces` to control which Namespaces' `SveltosCluster` can use this Identity
- This allows applying the same mechanism to both management clusters and other workload clusters

### 2. Reduce `sc-manager` permissions
- Moving away from direct Secret management to using `ControllerIdentity` for external authentication means `sc-manager` won't need to use Secrets, allowing reduction of CRUD permissions

### 3. Design to coexist with AWS and other Identities
- Like CAPA, utilize mechanism to progressively assume roles from initial IAM role (root role), making it compatible with Sveltos' authorization method
- Example:
  - mgmt IAM role → Assume Role for worker IAM role → Issue necessary tokens
  - In Sveltos, define `ControllerIdentity` as single resource or multiple layers, expressing multi-stage role switching through mutual references

```yaml
apiVersion: lib.projectsveltos.io/v1beta1
kind: SveltosCluster
metadata:
  labels:
    sveltos-agent: present
  name: mgmt
  namespace: mgmt
spec:
  identityRef:
    kind: ControllerIdentity
    name: worker-account-role
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSClusterControllerIdentity
metadata:
  name: "default"
spec:
  allowedNamespaces: {}  # Allow usage in all Namespaces
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSClusterRoleIdentity
metadata:
  name: mgmt-account-role
spec:
  allowedNamespaces:
  - test
  roleARN: "arn:aws:iam::123456789:role/CAPARole"
  sessionName: cluster-manager
  sourceIdentityRef:
    kind: AWSClusterControllerIdentity
    name: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSClusterRoleIdentity
metadata:
  name: worker-account-role
spec:
  allowedNamespaces:
  - test
  roleARN: "arn:aws:iam::987654321:role/CAPARole"
  sessionName: cluster-manager
  externalID: "xxxxxx"
  sourceIdentityRef:
    kind: AWSClusterRoleIdentity
    name: mgmt-account-role
```

### 4. Specific Use Cases
- For EKS, grant [AWS Pod Identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_pod_identity_association) to `projectsveltos` ServiceAccount in `projectsveltos` Namespace and grant minimum required permissions to cluster manager through Assume Role
- Obtain Token and grant necessary resource operation permissions through Kubernetes RBAC (ClusterRole/ClusterProfile)
  - This aligns with the most secure push-model operation recommended by multicluster SIG

## Benefits
- Flexible permission design through multi-stage role assumption
- Granular authentication management on Sveltos side, freeing from Secret storage and bloated RBAC management
- Enhanced security (principle of least privilege)
- Easy integration with EKS and other clouds

## Requests
- Creation of new CRD (ControllerIdentity) and implementation of `identityRef` support in `SveltosCluster`
- Consider architecture changes to eliminate need for Secret CRUD permissions in `sc-manager`
- Documentation and/or support on how to define role chains and relationship with external CRDs (like CAPA)

## Reference Links
- Multicluster SIG recommendation: https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/4322-cluster-inventory#push-model-with-identity-federation-recommended
- Explanation of CAPA's AWSClusterControllerIdentity and AWSClusterRoleIdentity: https://cluster-api-aws.sigs.k8s.io/topics/multitenancy
- Associate an IAM Role with a Pod. [aws\_eks\_pod\_identity\_association | Resources | hashicorp/aws | Terraform | Terraform Registry](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_pod_identity_association)
- Link EKS IAM and Kubernetes users and groups to grant permissions.: [aws\_eks\_access\_entry | Resources | hashicorp/aws | Terraform | Terraform Registry](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_access_entry)

Please consider this request. If you have any questions or opinions regarding the policy, I would appreciate your feedback.
