### ISSUE TITLE
Feature Request: Support exec plugin in Sveltos

### ISSUE THREAD

**Issue by kahirokunn** [projectsveltos/sveltos#445]
## Overview
Currently in Sveltos, authentication information is provided using kubeconfig to access clusters. However, in Kubernetes as a service like GKE, tokens have short expiration periods (e.g., 48 hours) and require regular updates. Furthermore, when using managed Kubernetes services, it is common to dynamically obtain tokens provided by vendor-specific authentication mechanisms.  
In such cases, `kubectl` natively supports "exec plugin" and its use is recommended as one of the best practices. Therefore, we would like to add exec plugin support to Sveltos to enable automatic authentication token retrieval from managed services.

## Background / Motivation
- Taking GKE as an example, access tokens expire in 48 hours, necessitating an automatic renewal mechanism.  
- Other Kubernetes managed services like EKS also use vendor-specific authentication infrastructure for token retrieval. The challenge is how to handle the required CLI and libraries for using this infrastructure in Sveltos.  
- If "exec plugin" can be used like kubectl, users can continue using their familiar kubeconfig settings, and operations can dynamically obtain and update tokens using managed service-specific CLIs.

### Example: kubeconfig with exec plugin when using EKS
As shown below, `exec` is specified in the users section, executing `aws eks get-token` to obtain the token.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: yyyy
    server: https://xxxx.gr7.ap-northeast-1.eks.amazonaws.com
  name: arn:aws:eks:ap-northeast-1:ooooo:cluster/sveltos-mgmt
contexts:
- context:
    cluster: arn:aws:eks:ap-northeast-1:ooooo:cluster/sveltos-mgmt
    user: arn:aws:eks:ap-northeast-1:ooooo:cluster/sveltos-mgmt
  name: arn:aws:eks:ap-northeast-1:ooooo:cluster/sveltos-mgmt
current-context: arn:aws:eks:ap-northeast-1:ooooo:cluster/sveltos-mgmt
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ap-northeast-1:ooooo:cluster/sveltos-mgmt
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-northeast-1
      - eks
      - get-token
      - --cluster-name
      - sveltos-mgmt
      - --output
      - json
      command: aws
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

## Expected Approaches
1. Enable all controllers to use AWS CLI and other necessary vendor CLIs.  
   - Prepare images with pre-installed CLIs for deployment in each container and enable execution across all controllers.  
   - When kubeconfig uses the `exec` plugin, automatically obtain tokens using that CLI.  
   - For CLI injection mechanisms, [content utilizing Nix](https://qiita.com/reoring/items/a3194b91067b86f65574) might be helpful as reference.

2. Set up a dedicated controller like Token Resolver Controller.  
   - Inject CLIs only into this controller as sidecars or init containers to obtain necessary tokens.  
   - Create a mechanism for this controller to redistribute and manage updated kubeconfig within Sveltos.  
   - Through centralized management, token updates can be controlled while minimizing CLI installations.

## Expected Benefits
- Reduced operational overhead in managing authentication token updates for managed services.  
- Enables configuration aligned with managed Kubernetes service best practices, allowing users to directly utilize their existing kubeconfig mechanisms.  
- By clarifying CLI installation locations and update mechanisms, security and operational management (version upgrades, installation oversight, etc.) can be handled more reliably.

## Suggestions/Requests
- Please add native support for exec plugin in Sveltos, enabling the use of CLI commands defined in the users section of kubeconfig files.  
- Please provide either a mechanism for executing CLIs on the Sveltos controller side or a dedicated mechanism like Token Resolver Controller.  
- It would be convenient if users could define options and extension points for automatic token updates.

Thank you for your consideration.
