### ISSUE TITLE
update documentation for private registries

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/sveltos#450]
When connecting to private registries, Sveltos accept a Secret of type kubernetes.io/dockerconfigjson. But it can also accept a Secret with just username and password.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cred1
  namespace: default
data:
  username: YWRtaW4=
  password: SGFyYm9yMTIzNDU=
```

with ClusterProfile

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: projectsveltos
spec:
  clusterSelector:
    matchLabels:
      env: fv
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    oci://harbor.XXXX.k8s.civo.com/library
    repositoryName:   projectsveltos
    chartName:        projectsveltos
    chartVersion:     0.44.3
    releaseName:      projectsveltos
    releaseNamespace: projectsveltos
    helmChartAction:  Install
    registryCredentialsConfig:
      insecureSkipTLSVerify: true
      credentials:
        name: cred1
        namespace: default
```
