### ISSUE TITLE
Feature Request: Enable HealthCheck resource's resourceSelectors to reference resources in the management cluster

### ISSUE THREAD

**Issue by kahirokunn** [projectsveltos/sveltos#458]
Sveltos HealthCheck is used to select various resources on a cluster and collect/evaluate their states.  
Typically, `resourceSelectors` specifies resources within the same cluster, but there may be cases where you want to reference resources in the management cluster.  
As an example of a possible extension, we could add a parameter called `local: true` to indicate "this is a reference to a management cluster resource" as shown below.

Here's an example handling KeptnMetric:

```yaml:config/healthcheck.yaml
apiVersion: lib.projectsveltos.io/v1beta1
kind: HealthCheck
metadata:
  name: cluster-metrics-check
spec:
  resourceSelectors:
    - group: metrics.keptn.sh
      version: v1
      kind: KeptnMetric
      local: true  # Add this to reference resources in the mgmt cluster

  # HealthCheck evaluation logic (Lua script)
  evaluateHealth: |
    function evaluate()
      -- Table to store results
      local hs = {
        resources = {}
      }

      local httpSuccessRate          = 0
      local kubeletErrorRate         = 0
      local kubeApiserverErrorRate   = 0

      -- Get metric values from all resources that HealthCheck retrieved
      for _, resource in ipairs(resources) do
        if resource.metadata and resource.metadata.name then
          if resource.metadata.name == (ctx.Cluster.metadata.name .. "-http-success-rate-metric") then
            httpSuccessRate = tonumber(resource.status and resource.status.value) or 0
          elseif resource.metadata.name == (ctx.Cluster.metadata.name .. "-kubelet-error-rate-metric") then
            kubeletErrorRate = tonumber(resource.status and resource.status.value) or 0
          elseif resource.metadata.name == (ctx.Cluster.metadata.name .. "-kubeApiserver-error-rate-metric") then
            kubeApiserverErrorRate = tonumber(resource.status and resource.status.value) or 0
          end
        end
      end

      -- Health evaluation logic (example)
      local status = "Healthy"
      local message = "cluster is healthy"

      -- Mark as Degraded if httpSuccessRate is below threshold and kubelet + kubeApiserver errors exceed certain amount
      if httpSuccessRate <= 0.1 and (kubeletErrorRate + kubeApiserverErrorRate) >= 1.0 then
        status = "Degraded"
        message = "too many errors"
      end

      table.insert(hs.resources, { status = status, message = message })
      return hs
    end
```

### Benefits of this extension

- Can utilize metrics and resource information aggregated in the management cluster
- Can perform evaluations using the same HealthCheck resource even when monitoring and observability resources (Kubernetes objects) are separated into different clusters

### Considerations

- The implementation of `local: true` depends on operational design. Internally, there are several design approaches such as adding a separate `Remote` field or extending resourceSelector.

---

### Basic Concept

By allowing the following conditions to be specified in ClusterSet (or a CR that represents multiple clusters), more flexible operational designs become possible:

- "Mark when N or more become Degraded" (default 1)
- "Failover when marked state continues for M seconds" (default 0 seconds)
- "Failover when unstable state (repeatedly marked/unmarked) continues" (default 0 seconds)

### Sample Resource Example

Let's consider (hypothetically) extending the ClusterSet resource specification as follows:

```yaml:config/clusterset.yaml
apiVersion: cluster.sveltos.io/v1beta1
kind: ClusterSet
metadata:
  name: demo-clusterset
spec:
  # HealthCheck policy at ClusterSet level (hypothetical extension)
  healthCheckPolicy:
    # How many Clusters' HealthChecks need to be Degraded
    degradedCount: 1

    # How long should the degradedCount state continue before Failover?
    degradeDuration: 5m

    # Failover when unstable state continues (repeatedly marked/unmarked)
    unstableDuration: 10m
```

### Concrete Examples (Conceptual)

- For frontend clusters, even if one becomes Degraded, it might be a momentary spike, so route to backup cluster after 5 minutes of continuation
- For batch clusters, don't failover unless 2 consecutive Degraded states occur since retries can handle some failures
- For infrastructure clusters running shared libraries, perform immediate failover

By setting failover policies per ClusterSet, you can establish flexible availability strategies for each environment.

---

## Future Prospects

- Enable evaluation scripts to be written in deno or python, not just lua
- Instead of script languages like lua, execute Pods and evaluate their results (Completed/Failed)
- Allow users to manually trigger and cancel each failover step
