### ISSUE TITLE
Feature Request: Control failover based on Degraded of `HealthCheck` conditions in ClusterSet / Set

### ISSUE THREAD

**Issue by kahirokunn** [projectsveltos/sveltos#459]
### Basic Concept

By allowing the following conditions to be specified in ClusterSet (or a CR that represents multiple clusters), more flexible operational designs become possible:

- "Mark when N or more become Degraded" (default 1)
- "Failover when marked state continues for M seconds" (default 0 seconds)
- "Failover when unstable state (repeatedly marked/unmarked) continues" (default 0 seconds)

### Sample Resource Example

Let's consider (hypothetically) extending the ClusterSet resource specification as follows:

```yaml:config/clusterset.yaml
apiVersion: cluster.sveltos.io/v1beta1
kind: ClusterSet
metadata:
  name: demo-clusterset
spec:
  # HealthCheck policy at ClusterSet level (hypothetical extension)
  healthCheckPolicy:
    # How many Clusters' HealthChecks need to be Degraded
    degradedCount: 1

    # How long should the degradedCount state continue before Failover?
    degradeDuration: 5m

    # Failover when unstable state continues (repeatedly marked/unmarked)
    unstableDuration: 10m
```

### Concrete Examples (Conceptual)

- For frontend clusters, even if one becomes Degraded, it might be a momentary spike, so route to backup cluster after 5 minutes of continuation
- For batch clusters, don't failover unless 2 consecutive Degraded states occur since retries can handle some failures
- For infrastructure clusters running shared libraries, perform immediate failover

By setting failover policies per ClusterSet, you can establish flexible availability strategies for each environment.

---

## Future Prospects

- Enable evaluation scripts to be written in deno or python, not just lua
- Instead of script languages like lua, execute Pods and evaluate their results (Completed/Failed)
- Allow users to manually trigger and cancel each failover step
