### ISSUE TITLE
Feature Request: Add CEL validation to explicitly prevent changes to specific custom resource fields

### ISSUE THREAD

**Issue by kahirokunn** [projectsveltos/sveltos#466]
## Overview

In `sveltos`, there are several behaviors where specific fields in Custom Resources (CRDs) are effectively immutable (changes are ignored). However, currently, it's not clear to users that "changes to these fields won't be reflected," and this isn't clearly documented (or is difficult to find in the documentation).

For such fields, we would like to introduce a mechanism using [Kubernetes CEL validation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#configure-validation) to prohibit changes (or return errors when changes are attempted).

## Details

- **Example target fields**
  - Specific sub-fields within `spec`
  - Effectively read-only fields where updates are not reflected

- **Expected behavior**
  - When users attempt to modify these fields using `kubectl apply` or similar commands, explicitly return an error or clearly indicate through documentation or messages that "this field cannot be modified"
  - This prevents user confusion from attempting unnecessary changes

## Implementation Example

While this is just an example, CEL validation can be used to check that "specific fields maintain the same value before and after updates." `oldSelf` is a CEL built-in variable available in Kubernetes 1.26 and later for referencing the resource value before updates.

```yaml:config/crd/sveltos_customresource.yaml
# Example: When foo field is immutable
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hoge.projectsveltos.io
spec:
  # ...
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                foo:
                  type: string
              x-kubernetes-validations:
              - rule: "self.foo == oldSelf.foo"
                message: "spec.foo cannot be updated"
```

By adding validation rules like above, when users try to modify this field, they'll receive a validation error explicitly indicating that the field is "immutable."

## Background

- There are many cases where specific fields need to be immutable for version control purposes
- Current behavior where changes are silently ignored can cause confusion for users and operators
- Providing error feedback in advance can prevent mistakes and reduce learning costs

## Benefits of This Proposal

- **Explicit Specification**:
  - Clearly indicate immutability in documentation and CRD schema
- **Reduced Bug Reports and Operational Errors**:
  - Fewer reports about "changes not taking effect," reducing unnecessary issues and support load
- **Improved Maintainability**:
  - Clearer update permissions make maintenance and backward compatibility management easier
