### ISSUE TITLE
Document HelmCharts with Flux Sources

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/sveltos#517]
```yaml
  helmCharts:
  - repositoryURL:    gitrepository://flux-system/flux-system/charts/projectsveltos
    releaseName:      projectsveltos
    releaseNamespace: projectsveltos
    helmChartAction:  Install
```

**Comment by gianlucam76** [comment]
@trejo08 taking a look. will update soon. thanks

**Comment by gianlucam76** [comment]
Hi @trejo08 I am running Sveltos v1.2.1 and I don't see any error. 

I deployed Flux on my **management** cluster:

```
flux bootstrap github  --owner=gianlucam76 --repository=helm-charts --branch=main --path=charts/projectsveltos --personal
``` 

this created a GitRepository 

```
kubectl get gitrepository -A                                                                                              
NAMESPACE     NAME          URL                                            AGE     READY   STATUS
flux-system   flux-system   ssh://git@github.com/gianlucam76/helm-charts   5m13s   True    stored artifact for revision 'main@sha1:ba2d41c33404ed06cc4315b08bedf01183160e6b'
```

At this point I deployed Sveltos in my **management** cluster 

```
helm install projectsveltos projectsveltos/projectsveltos -n projectsveltos --create-namespace
```

Posted this ClusterProfile:

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-sveltos
spec:
  clusterSelector:
    matchLabels:
      env: fv
  helmCharts:
  - repositoryURL: gitrepository://flux-system/flux-system/charts/projectsveltos
    releaseName: sveltos
    releaseNamespace: projectsveltos
    helmChartAction: Install
```

and Sveltos was deployed in my **managed** clusters 

```yaml
  apiVersion: config.projectsveltos.io/v1beta1
  kind: ClusterSummary
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"config.projectsveltos.io/v1beta1","kind":"ClusterProfile","metadata":{"annotations":{},"name":"deploy-sveltos"},"spec":{"clusterSelector":{"matchLabels":{"env":"fv"}},"helmCharts":[{"helmChartAction":"Install","releaseName":"sveltos","releaseNamespace":"projectsveltos","repositoryURL":"gitrepository://flux-system/flux-system/charts/projectsveltos"}]}}
    creationTimestamp: "2025-11-23T18:35:44Z"
    finalizers:
    - clustersummaryfinalizer.projectsveltos.io
    generation: 1
    labels:
      projectsveltos.io/cluster-name: clusterapi-workload
      projectsveltos.io/cluster-profile-name: deploy-sveltos
      projectsveltos.io/cluster-type: Capi
    name: deploy-sveltos-capi-clusterapi-workload
    namespace: default
    ownerReferences:
    - apiVersion: config.projectsveltos.io/v1beta1
      kind: ClusterProfile
      name: deploy-sveltos
      uid: 9c79170f-3f83-4464-9538-7f4937381f43
    resourceVersion: "5826"
    uid: c65d478b-ad6a-44d5-aa37-c3951dfa2bd6
  spec:
    clusterName: clusterapi-workload
    clusterNamespace: default
    clusterProfileSpec:
      clusterSelector:
        matchLabels:
          env: fv
      continueOnConflict: false
      continueOnError: false
      helmCharts:
      - helmChartAction: Install
        releaseName: sveltos
        releaseNamespace: projectsveltos
        repositoryURL: gitrepository://flux-system/flux-system/charts/projectsveltos
      reloader: false
      stopMatchingBehavior: WithdrawPolicies
      syncMode: Continuous
      tier: 100
    clusterType: Capi
  status:
    dependencies: no dependencies
    featureSummaries:
    - featureID: Helm
      hash: HYbIiVO1yMHaOxgd71M98tZiKWaCGWg4yh0QxFb+NGw=
      lastAppliedTime: "2025-11-23T18:35:54Z"
      status: Provisioned
    helmReleaseSummaries:
    - releaseName: sveltos
      releaseNamespace: projectsveltos
      status: Managing
      valuesHash: Eq4yyx7ALQHto1gbEnwf7jsNxTVy7WuvI5choD2C4SY=
``

**Comment by gianlucam76** [comment]
Thank you @trejo08 for sharing those extra details. I will try this again tomorrow and after first deployment I will change something in the clusterProfile and in the helm chart itself to cause a new reconciliation. Will update back here. Thanks again

**Comment by trejo08** [comment]
Hi @gianlucam76 sorry for my delay, I didn't realized of your comments, regarding the info you requested me:
1 - I'm running on v1.2.1
2 - At the beginning I've added the helmChart using gitrepository as source, them, I tried to update some values of the chart, doing rebalancing and other minor configs for the charts, then after that I got those errors as I showed, this always is passing me, even if I reinstall in a fresh cluster, just created at GKE and bootstrapped with terraform flux provider, using those steps, At first/fresh install all works well but if I change a minimun value on the chart or even if I push something not related to chart but in the same gitops/flux repo, all the charts referenced to gitrepository/helmchart enter in a loop of that message and the uniq workaround that I found is, package the chart and upload to ArtifactRegistry from GCP(in my case, could be any other helm selfhosted like AWS, Azure or even a public git repository) and swith to OCI URL, the issue appears when you reference a chart inside the flux repo and them update any resource in the same repo

I'll get some logs and put them here

**Comment by gianlucam76** [comment]
is path included?

For instance here

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-sveltos
spec:
  clusterSelector:
    matchLabels:
      env: fv
  helmCharts:
  - repositoryURL: gitrepository://flux-system/flux-system/charts/projectsveltos
    releaseName: sveltos
    releaseNamespace: projectsveltos
    helmChartAction: Install
```

notice 

repositoryURL: gitrepository://flux-system/flux-system/charts/projectsveltos

can _GitRepository_ in the _flux-system_ namespace, named _flux-system_ contains the Sveltos helm chart in the directory _charts/projectsveltos_

Otherwise Sveltos looks at the entire repo.

**Comment by gianlucam76** [comment]
Thank you @trejo08 . I can see the error **invalid semantic version** in the clusterSummary now 

```yaml    
featureSummaries:
    - consecutiveFailures: 1
      failureMessage: invalid semantic version
      featureID: Helm
      hash: NCk+v2aWfjJvncISSqmh8PAJzOI9iE+1GDMDZhfeIlI=
      lastAppliedTime: "2025-11-27T20:22:41Z"
      status: Failed
```

the problem is when using Helm chart from GitRepository, Sveltos is not properly getting the version (it actually does not set it, so it stays empty which leads to " invalid semantic version" when you change anything).

**I will fix that.** 

Meanwhile, if you set it yourself in the clusterProfile it will work. For instance 

```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-sveltos
spec:
  clusterSelector:
    matchLabels:
      env: fv
  helmCharts:
  - repositoryURL: gitrepository://flux-system/flux-system/charts/projectsveltos
    releaseName: sveltos
    releaseNamespace: projectsveltos
    helmChartAction: Install
    chartVersion: 1.2.1
    values: |
      addonController:
        controller:
          image:
            tag: v1.2.1
          resources:
            requests:
              memory: 256Mi
```

note the **chartVersion: 1.2.1**
